name: pdam
description: "Alirin — Aplikasi Tagihan PDAM"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  http_parser: ^4.0.2
  shared_preferences: ^2.2.0
  crypto: ^3.0.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/air.png
    - assets/images/panah.png
    - assets/images/Alirin.png
    - assets/images/Alirin logo.png
    - assets/images/Frame 651.png
    - assets/images/Frame 652.png